### ISSUE TITLE
VenusLens.sol contract is not verified on BSC mainnet

### ISSUE THREAD

**Issue by wanglonghong** [VenusProtocol/venus-config#1]
Hi, venus technical team!
All of the contracts are verified on bsc mainnet except venuslens.sol
0x595e9DDfEbd47B54b996c839Ef3Dd97db3ED19bA

Is there any reason you didn't verifiy and publish?

**Comment by kkirka** [comment]
The current versions of all contracts are verified. Please check the contract packages in the repo to know the contract addresses
