### ISSUE TITLE
VenusLens contract will never be used? 

### ISSUE THREAD

**Issue by wanglonghong** [VenusProtocol/venus-config#2]
![image](https://user-images.githubusercontent.com/30057497/113514271-3fa4c100-95a0-11eb-921e-75e3ba025b86.png)

![image](https://user-images.githubusercontent.com/30057497/113514288-51866400-95a0-11eb-9c00-83d37777d3e2.png)

**Comment by kkirka** [comment]
VenusLens is a view contract, meaning that no transactions to this contract should ever happen. This doesn't mean that it isn't used though – you can use lens to get aggregated data from chain. Please see the latest version of this and other contracts in the corresponding package (https://github.com/VenusProtocol/venus-protocol)
