### ISSUE TITLE
Why is the information on the document different from the information on the chain?

### ISSUE THREAD

**Issue by xioamal** [VenusProtocol/venus-config#7]
Is the project not maintained? Why hasn't the contract address been updated?

**Comment by kkirka** [comment]
You can find the up to date contract addresses in the corresponding packages. The current links (may change in the future, please follow package updates for more info):
* For the core pool: https://github.com/VenusProtocol/venus-protocol/blob/f4a1a4606c707cc4813cee0554dc307cd80dbbd0/networks/mainnet.json
* For the isolated pools: https://github.com/VenusProtocol/isolated-pools/blob/master/deployments/bscmainnet.json
* For the oracle: https://github.com/VenusProtocol/oracle/tree/master/deployments/bscmainnet
